import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import styles from "../styles/Home.module.css";
import { Welcome } from "../types";

type props = {
  res: Welcome[];
};

export const getStaticProps: GetStaticProps = async () => {
  const res = await fetch("https://kontests.net/api/v1/all");
  const result = await res.json();

  return {
    props: {
      res: result,
    },
  };
};

export const Blog = ({ res }: props) => {
  return (
    <>
      {res.map((element, index) => (
        <p key={index}>
          <a href={element.url}>{element.site}</a>
        </p>
      ))}
    </>
  );
};

const Home: NextPage<props> = ({ res }: props): JSX.Element => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Blog res={res} />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
