import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";

import styles from "../styles/Home.module.css";
import { In24_Hours, Welcome } from "../types";

type props = {
  res: Welcome[];
};

// TODO  move this to lib folder
const shuffleArray = (array: Array<any>) => {
  let currentIndex: number = array.length;
  let randomIndex: number;
  while (currentIndex != 0) {
    randomIndex = Math.floor(Math.random() * currentIndex);
    currentIndex--;
    [array[currentIndex], array[randomIndex]] = [
      array[randomIndex],
      array[currentIndex],
    ];
  }
  return array;
};

// TODO  move this to lib folder
export const filterElementIfNotHappeningIn24Hours = (array: Welcome[]) => {
  let result: Welcome[] = [];

  array.forEach((element: Welcome) => {
    if (element.in_24_hours === In24_Hours.Yes) {
      result.push(element);
    }
  });

  return result;
};

export const getServerSideProps: GetServerSideProps = async () => {
  const res = await fetch("https://kontests.net/api/v1/all");
  let resultJson = await res.json();
  const result = filterElementIfNotHappeningIn24Hours(resultJson);
  shuffleArray(result);

  return {
    props: {
      res: result,
    },
  };
};

// TODO move this to component folder
export const EventCard = ({ res }: props) => {
  const data: Welcome = res[0];

  return (
    <a className={styles.card} href={data.url}>
      <h3>{data.name}</h3>
    </a>
  );
};

const Home: NextPage<props> = ({ res }: props): JSX.Element => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <span className={styles.title}>Take a Challenge</span>
        <span className={styles.description}>all challenges provided start in less than 24hrs</span>
        <EventCard res={res} />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
